version: "2.1"
services:
  tests:
    image: golang:1.15
    working_dir: /go/src/github.com/peterstace/simplefeatures
    entrypoint: go test -covermode=count -coverprofile=coverage.out -test.count=1 -test.run=. ./geom ./rtree
    volumes:
      - ..:/go/src/github.com/peterstace/simplefeatures
    environment:
      - GO111MODULE=on
